<a href="https://colab.research.google.com/github/mhdossey/Numpy_Pandas_Assignment/blob/main/PandasandNumpyAssignment_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Assignment_PANDAS_NUMPY.ipynb

In [3]:

import numpy as np
import pandas as pd


1) Generate an array of zeroes using inbuilt numpy function.


In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

2) Run the given code and find the dot product of both arrays.

In [23]:
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
a
b

array([[6, 5, 3],
       [6, 9, 8],
       [3, 8, 3],
       [9, 2, 4]])

In [24]:
a.dot(b)

array([[ 90,  80,  66],
       [108, 151, 101],
       [162, 133, 108]])

In [67]:
print(np.dot(a,b))

[[ 90  80  66]
 [108 151 101]
 [162 133 108]]


In [26]:
b.dot(a)

array([[ 58,  74,  69,  63],
       [106, 127, 125, 115],
       [ 52,  83,  90,  60],
       [ 72,  70,  52,  74]])

3)Read the csv file provided using pandas and display the first 5 entries

In [30]:
data = pd.read_csv('/content/drive/MyDrive/data.csv')

In [31]:
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  
0   0.135641  
1   0.080067  
2   0.119868  
3   0.128733  
4   0.125546

4)Describe the data with all features

In [68]:
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   OBJECTID     25 non-null     int64  
 1   UNIT_NAME    25 non-null     object 
 2   DESCRIPTION  25 non-null     object 
 3   ACRES        25 non-null     float64
 4   SHAPE.AREA   25 non-null     float64
 5   SHAPE.LEN    25 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.3+ KB


5)Find the total count of missing values for each feature.

In [35]:
data.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

6)Display all the unique values from the 'DESCRIPTION’ column.

In [69]:
data.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.

In [74]:
data.groupby('DESCRIPTION').apply(lambda x:x.mean(axis=1))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.


DESCRIPTION              
Interpretive Center    8       10.931695
State Natural Area     16      75.476802
                       20      53.869319
State Nature Preserve  18      33.732628
                       19      28.083480
State Park             0      151.903981
                       1       73.810049
                       2      214.897567
                       3      239.477294
                       4      246.114004
                       5      239.116793
                       6      383.935737
                       7      138.235169
                       10    1631.061723
                       11      23.763512
                       14     202.106399
                       15     193.428041
                       23     153.562633
State Recreation Area  9       10.352350
                       12      21.563030
                       13      70.790160
                       17      14.893326
                       21     320.079854
                       22     1

8)Generate a random sample of 10 rows from the data.

In [49]:
data.shape
data.sample(n=10)

OBJECTID                            UNIT_NAME            DESCRIPTION  \
21        43  Pembina Gorge State Recreation Area  State Recreation Area   
10        31           Little Missouri State Park             State Park   
11        32               Sully Creek State Park             State Park   
5         26                 Icelandic State Park             State Park   
18        39      Gunlogson State Nature Preserve  State Nature Preserve   
1         22               Beaver Lake State Park             State Park   
4         25            Grahams Island State Park             State Park   
9         30    Fort Mandan State Recreation Area  State Recreation Area   
20        41    Missouri River State Natural Area     State Natural Area   
2         23      Fort Abraham Lincoln State Park             State Park   

      ACRES  SHAPE.AREA  SHAPE.LEN  
21  1236.98    0.000615   0.338800  
10  6492.93    0.003136   0.313756  
11    63.03    0.000030   0.024016  
5    930.30    0.000461   0.166712  
18    95.89    0.000048   0.040465  
1    273.16    0.000129   0.080067  
4    959.33    0.000469   0.125546  
9     11.40    0.000005   0.009396  
20   174.39    0.000083   0.087192  
2    836.47    0.000399   0.119868

9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

In [76]:
new_feature = pd.Series(np.random.random(len(data)))

In [80]:
data['new_feature'] = new_feature

In [81]:
data

OBJECTID                                   UNIT_NAME  \
0         21                   Fort Stevenson State Park   
1         22                      Beaver Lake State Park   
2         23             Fort Abraham Lincoln State Park   
3         24                      Fort Ransom State Park   
4         25                   Grahams Island State Park   
5         26                        Icelandic State Park   
6         27                   Lake Metigoshe State Park   
7         28                  Lewis and Clark State Park   
8         29         Lewis and Clark Interpretive Center   
9         30           Fort Mandan State Recreation Area   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
12        35        Butte St. Paul State Recreation Area   
13        36       Crow Flies High State Recreation Area   
14        33                     Turtle River State Park   
15        34                   Lake Sakakawea State Park   
16        37                  Elkhorn State Natural Area   
17        38         Fahlgren Park State Recreation Area   
18        39             Gunlogson State Nature Preserve   
19        40  Head of the Mountain State Nature Preserve   
20        41           Missouri River State Natural Area   
21        43         Pembina Gorge State Recreation Area   
22        44       Turtle Mountain State Recreation Area   
23        45                      Cross Ranch State Park   
24        42         Pelican Point State Recreation Area   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  new_feature  
0              State Park   586.48    0.000284   0.135641     0.295676  
1              State Park   273.16    0.000129   0.080067     0.642543  
2              State Park   836.47    0.000399   0.119868     0.807103  
3              State Park   933.78    0.000444   0.128733     0.533177  
4              State Park   959.33    0.000469   0.125546     0.484124  
5              State Park   930.30    0.000461   0.166712     0.650593  
6              State Park  1508.53    0.000751   0.212196     0.084351  
7              State Park   524.81    0.000256   0.130420     0.948238  
8     Interpretive Center    14.71    0.000007   0.016774     0.405588  
9   State Recreation Area    11.40    0.000005   0.009396     0.075348  
10             State Park  6492.93    0.003136   0.313756     0.287366  
11             State Park    63.03    0.000030   0.024016     0.437870  
12  State Recreation Area    51.23    0.000025   0.022095     0.838577  
13  State Recreation Area   247.11    0.000120   0.050518     0.110304  
14             State Park   775.28    0.000378   0.145220     0.453116  
15             State Park   739.52    0.000357   0.191806     0.869127  
16     State Natural Area   264.84    0.000127   0.067082     0.382835  
17  State Recreation Area    21.56    0.000010   0.013294     0.140027  
18  State Nature Preserve    95.89    0.000048   0.040465     0.357249  
19  State Nature Preserve    72.30    0.000034   0.033885     0.580962  
20     State Natural Area   174.39    0.000083   0.087192     0.800864  
21  State Recreation Area  1236.98    0.000615   0.338800     0.153878  
22  State Recreation Area   695.04    0.000345   0.086487     0.351644  
23             State Park   569.07    0.000274   0.180257     0.886517  
24  State Recreation Area    25.22    0.000013   0.026357     0.668870

10) Replace zero value of column 'OBJECTID' with mean value permanently.

In [86]:
data.OBJECTID[data.OBJECTID == 0]

Series([], Name: OBJECTID, dtype: int64)

OBJECTID Column doesn't have any null values 

In case it had any null values,we fix it with this code

In [ ]:
data['OBJECTID'].fillna(data.OBJECTID.mean())